export const state = {
  projects: [],
  project: null,
  projectId: "",
  board: null,
  ticketDetail: null,
  selectedTicketId: "",
  tickets: [],
  repos: [],
  mergeQueue: [],
  events: [],
  artifacts: [],
  activityFilters: {
    ticketId: "",
    type: "",
    limit: 20,
  },
  boardFilters: {
    search: "",
    state: "",
    assignedRole: "",
    priority: "",
  },
  live: {
    eventSource: null,
    reconnectTimerId: 0,
    refreshTimerId: 0,
    isConnected: false,
    status: "idle",
    lastEventAt: "",
    lastCursor: "",
    lastSequence: 0,
  },
};
